### ISSUE TITLE
En el código de la página aparecen contraseñas

### ISSUE THREAD

**Issue by ethyrie** [Desch/DynWeb#1]
Y si me cago en tu puta madre? O te meto una citación judicial por el culo? Que? Eh payasete?

**Comment by Desch** [comment]
No me digas. Te has puesto muy tonto sin motivo y yo puedo seguirte el juego.
No se que vas a denunciar, es un git y lo subiste tu...por tanto yo no he hecho nada, has sido tu mismo el que lo ha publicado.

Si dejas de insultarme, de tocarme los cojones, esto se para y cada uno por su lado. Mientras que sigas intentado ofender yo te seguiré el juego.

Que no me digas luego que no he sido buena persona e intentar parar estas tonterias de niños pequeños, que sinceramente me aburren mucho.

Un saludo
Desch

**Comment by Desch** [comment]
Mira la diferencia, tu me insultas todo el tiempo y yo al menos tengo la decencia de hablarte con educación. En todo lo que he dicho no te he insultado ni una sola vez, mientras que tu con el gilipollas todo el día en la boca.

**Comment by ethyrie** [comment]
Es que me da igual
La verdad
Yo lo subí, y me echaste del repo, y despues pasaste de un git privado a publico. Pues ole
Ni si quiera me voy a leer lo que has puesto me la soplas xDDDD
Es que si eres gilipollas y demuestras todo el rato que lo eres con cosas así no esperes que te llame otra cosa. Por que empezar a jugar a publicar lo del otro es de que tienes que ser gilipollas y ya.

**Comment by ethyrie** [comment]
Pero es que me la sopla en realidad, las contraseñas ya estan cambiadas y la web es una plantilla de yootheme con 3 cosas cambiadas. A años luz esta ahora.

**Comment by ethyrie** [comment]
O sea que tu quedate con la web pero recuerda que te ganaste el apodo de gilipollas y voy a conseguir que la gente lo use. Desch el gilipollas

**Comment by Desch** [comment]
Jajajaa que triste eres.
Si te crees que la gente va a llamarme así porque lo diga un mierdas como tu va a ser que no.

Ni te voy a responderas.

**Comment by ethyrie** [comment]
Mierdas xDDDDD
Cuando quieras te follo hasta que se te salgan los ojos, que lo necesitas.

**Comment by Desch** [comment]
Que si campeón.
Que eres muy machote detrás de la pantalla...realmente es lo único que tienes.

Puedo sentir hasta pena por ti...que lástima me das.

**Comment by ethyrie** [comment]
Que que dices de que unico que tengo
Ni puta idea JAJAJAJAJAJAJAJA

**Comment by Desch** [comment]
Me aburres. Tengo cosas mejores que hacer.
Sigue con tu twitter diciendo esa sarta de to tonterias que parece que te hace feliz.

**Comment by ethyrie** [comment]
A mi no me aburres, voy a seguir tocando los cojones una buena temporada o hasta que borres esto, que no tiene ni pizca de broma

Bueno creo que toca ahora que te reporte a yootheme por publicar sus cosas

**Comment by ethyrie** [comment]
Que no te sale de los cojones? Bueno tengo una larga vida por delante durante la cual no me importaria invertir algo de su tiempo util en convertir de tu existencia un infierno. Un saludo

**Comment by Desch** [comment]
Uy si, mi vida depende tanto de tu existencia...que no podré soportarlo.
Madre mia que depresión me está entrando...tengo que saltar por la ventana..

Pesado.

**Comment by ethyrie** [comment]
Bueno venga hasta luego que te motivas y dejas de hacer lo que llaman "lectura comprensiva"
No me interesas si no entiendo lo que digo.
https://open.spotify.com/track/1JLCIFeSYTYcQGXCtuxEsF
